### ISSUE TITLE
does not start squeezelite

### ISSUE THREAD

**Issue by martin-77** [oweitman/squeeze-bluetooth#1]
First of all thanks for your work.
But: it does not work. The Speaker connects to the raspi, but squeezlite does not start a new instance.
My config: Raspi3, new install of raspbian (buster!!!), using internal bluetooth, latest squeezelite

if i run manual squeezelite -o bluealsa:HCI=hci0,DEV=XX:XX:XX:XX:XX:XX,PROFILE=a2dp -n Speaker, the server finds the Speaker and plays without any problems.
Maybe it is related to the btspeaker-moitor.py script, cause it claims about a deprecated object.

> root@raspberrypi:/etc/pyserver./btspeaker-monitor.py
> 
> ./btspeaker-monitor.py:85: PyGIDeprecationWarning: GObject.MainLoop is deprecated; use > GLib.MainLoop instead
  mainloop = gobject.MainLoop()
^CTraceback (most recent call last):
  File "./btspeaker-monitor.py", line 86, in <module>
    mainloop.run()
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 498, in run
    super(MainLoop, self).run()
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/gi/_ossighelper.py", line 251, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)

**Comment by oweitman** [comment]
ok, maybe this was easy ti fix. i am wondering that last week there was no depreciation error, but i didnt tried it with the new raspian buster. maybe the used software packages are also upgraded to newer versions.
i have to test it with buster

if you want to test this you can change in file btspeaker-monitor.py:

`from gi.repository import GObject as gobject`
to
`from gi.repository import GLib as glib`

and

`mainloop = gobject.MainLoop()`
to
`mainloop = glib.MainLoop()`

**Comment by oweitman** [comment]
closed df66a83 and dfc6876
