### ISSUE TITLE
not working on bullseye

### ISSUE THREAD

**Issue by cis202** [oweitman/squeeze-bluetooth#10]
I had this working before, but this time I tried it on a new install of Raspberry Pi OS Lite, a port of debian bullseye.
And it fails with this error:
Dec 11 17:51:07 btmine systemd[1]: Started Bluetooth Speaker Connectionmonitor.
Dec 11 17:51:07 btmine btspeaker-monitor[2247]: Traceback (most recent call last):
Dec 11 17:51:07 btmine btspeaker-monitor[2247]:   File "/etc/pyserver/btspeaker-monitor.py", line 9, in <module>
Dec 11 17:51:07 btmine btspeaker-monitor[2247]:     from gi.repository import GLib as glib
Dec 11 17:51:07 btmine btspeaker-monitor[2247]: ModuleNotFoundError: No module named 'gi'
Dec 11 17:51:07 btmine systemd[1]: btspeaker-monitor.service: Main process exited, code=exited, status=1/FAILURE
Dec 11 17:51:07 btmine systemd[1]: btspeaker-monitor.service: Failed with result 'exit-code'.
I am not very good in debugging this, that 's why I post it here.

Thanks for the great job you did. Hope you solve this one too.

**Comment by oweitman** [comment]
i seems that the lib gi.repository is missing or a dependency that is used by this lib is missing.
did you had any error messages in step 3 or 4 in the install process?
please provide the text output

actually i didnt use this solution any more and cant reproduce by my self

**Comment by cis202** [comment]
I can't remember any errors. I reinstalled dbus-python to get some logging. Attaching the logs from apt, pip3 & build.
[rpi-BT.tar.gz](https://github.com/oweitman/squeezelite-bluetooth/files/10215390/rpi-BT.tar.gz)

**Comment by oweitman** [comment]
please try this.
i found this as a solution here
https://stackoverflow.com/questions/70329976/modulenotfounderror-no-module-named-gi-how-can-i-fix-it
`
sudo apt install libcairo2-dev libxt-dev libgirepository1.0-dev 

pip3 install PyGObject pycairo
`

**Comment by cis202** [comment]
You can close this as I don't think it is related to bullseye.
