### ISSUE TITLE
The btspeaker-monitor.service requires a lms user

### ISSUE THREAD

**Issue by coissac** [oweitman/squeeze-bluetooth#4]
The demon `btspeaker-monitor.service` requires a `lms`user on the box which is not a standard user:

At the line 7 of the script `btspeaker-monitor.service`

```{bash}
User=lms
``` 
If such user doesn't exist then the daemon cannot be run. Can you switch to the standard `pi` user or better add the command to create the `lms` user in your tutorial.

```{bash}
adduser --disabled-login \
        --no-create-home \
        --add_extra_groups  lms
``` 

Thanks for your work

All the best

**Comment by oweitman** [comment]
thank you for your improvements.
i added/adjusted the tutorial

**Comment by coissac** [comment]
Hi,

Always in the context of my reinstall, this time I added a `lms` user and add to modify a bit the command to create the user : 

```bash
adduser --disabled-login \
        --no-create-home \
        --system  lms
```
Like that the user is more tailored to its usage.

I had also to add the new user to the audio group to allow it to play music 😉 

```bash
addgroup lms audio
```

All the best
Eric
