### ISSUE TITLE
One more missing dependency

### ISSUE THREAD

**Issue by coissac** [oweitman/squeeze-bluetooth#5]
Hi again,

I had to rebuilt again from scratch my system yesterday. And realize that a supplementary package was needed to allow for connection of the Bluetooth device. I don't understand why because in my mind Blaez was supposed to include piulse-audio. Without it the device pairs, can be trusted but connect and disconnect instantaneously. I found the trick on a forum but I lost the link. 
Whatever that extra dependency solve instantaneously the problem.

```bash
sudo apt-get install pulseaudio-module-bluetooth
```

Cheers

Eric

**Comment by oweitman** [comment]
hm, maybe the bluez project focus more on pulseaudio and not alsa.
i also have to recreate my raspberry LMS-Server.
i test this and then i ad it to the guide

**Comment by coissac** [comment]
You can have a look at the following script that list all my shell command to install mine.

https://github.com/coissac/jukebox/blob/master/jukebox.sh <https://github.com/coissac/jukebox/blob/master/jukebox.sh>

All the best

Eric

**Comment by oweitman** [comment]
thank you for your input.
today i testet my actual documentation and everything works.
