### ISSUE TITLE
No sound out of squeezelite

### ISSUE THREAD

**Issue by gahisee** [oweitman/squeeze-bluetooth#6]
Followed instructions to the letter and yes, upon RPI boot, the bluetooth speaker is connected.
Playing Spotify on squeezelite produces no sound.
The output option is set to "default." How is it connected to bluetooth?

**Comment by oweitman** [comment]
the library bluez is responsible for the bluetooth communication.
the library alsa is responsible for audio output
the library bluez-alsa connects theese two things and redirects the default audio output of the raspberry
to the conneted bluetoothdevice

More details you can find here https://github.com/Arkq/bluez-alsa

did you test the audio output of your raspberry without bluetooth?
you can test/play with the alsa-tools speaker-test and aplay

**Comment by gahisee** [comment]
after some fiddling and realizing that squeezelite-bluetooth renders a Spotify Connect device,
it all worked especially your handling of auto connections during boot up and bluetooth device power sequence.
i thank you for a good implementation.

**Comment by oweitman** [comment]
thank you and closed
